# Generated by Django 5.2.11 on 2026-02-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mcqresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='expected_output',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='test_input',
            field=models.TextField(default=''),
        ),
    ]
